### ISSUE TITLE
Service name is already in use on the network

### ISSUE THREAD

**Issue by ejb1123** [Apollon77/hap-controller-node#191]
Hello, I have been working on exposing the functionality found in this project to node-red. Sometime I have more then one discovery running from my machine and I get the error below. Would exposing the ability to set the service name help resolve this issue?  

```
3 Jun 22:38:55 - [error] Error: Service name is already in use on the network
    at Registry._onProbeComplete (/Users/user1/.node-red/node_modules/bonjour-hap/lib/Registry.js:108:27)
    at Prober.done (/Users/user1/.node-red/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/Users/user1/.node-red/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (node:events:513:28)
    at Socket.<anonymous> (/Users/user1/.node-red/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (node:events:513:28)
    at UDP.onMessage (node:dgram:930:8)
```

**Comment by NorthernMan54** [comment]
Something odd with your code, as you can have multiple discoveries running at the same time.

FYI - Have you looked at https://www.npmjs.com/package/node-red-contrib-homebridge-automation

**Comment by ejb1123** [comment]
@NorthernMan54 thank you for the response I found out this error was not related to this project and related to another project I was using. I will now close this issue.
